version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Starting pre-build phase
      - java -version
  build:
    commands:
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
      - ls
      - aws lambda update-function-code --function-name java-demo-lambda --zip-file fileb://target/DemoLambda-1.0.jar
artifacts:
  files:
    - target/DemoLambda*.jar
  discard-paths: yes

#fileb: đọc từ máy build local
